language: generic

services:
  - docker

install:
  - make build
  - docker images

script:
  - make daemon
  - docker ps
  - curl --proxy localhost:4000 http://httpbin.org/ip
  - curl --proxy localhost:4000 http://httpbin.org/ip
